version: '3.8'
services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/api
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password