version: '3.8'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
